### ISSUE TITLE
[Feature Request] Don't comment on posts with the link to the token already in them

### ISSUE THREAD

**Issue by StevenSavold** [Narase33/std_bot#4]
In the linked comment std_bot commented with the link to the new token (in this case std::transform) when the link was already put in the comment. 

https://www.reddit.com/r/cpp_questions/comments/myuvj4/finding_where_a_value_is_not_a_digit_and_then/gvx475e?utm_medium=android_app&utm_source=share&context=3

Is it possible to add a feature to std_bot where if the bot finds a new token, but them also sees the link to that token in the same comment that it does not make it's post?

**Comment by Narase33** [comment]
This is actually already on my ToDo list. Just didnt have the time yet to resolve this issue

**Comment by StevenSavold** [comment]
Oh great! If you would like I could take a first pass at it in my spare time and make a merge request

**Comment by Narase33** [comment]
Has been resolved in https://github.com/Narase33/std_bot/commit/938185a30da0121120362ead7549183362d3fa47
