### ISSUE TITLE
Comments about the python code

### ISSUE THREAD

**Issue by bstaletic** [Narase33/std_bot#5]
I've noticed a few things while reading the source:

1. You're importing both `urllib.request` and `requests`. They serve the same purpose.
1.1. The one place where `urllib.reuqest` was used can easily be replaced with `requests.get`.
2. You sometimes use `"{}".format()` and sometimes `f"{}'`.
2.1. If consistency is desired, this can also be easily fixed, but perhaps what you've written was intentional.
3. You're basically reinventing the `logging` standard module with `__log()`.
3.1. You can set the format of the logger, redirect stderr to a file, and then just call `logger.debug()`.
3.2. Logging the exceptions is pretty nice with `logging` too - `logger.error()` for when you don't want the stack trace and `logger.exception()` for when you do.

I can make a pull request, but I wanted to hear from you first.

**Comment by Narase33** [comment]
To be honest I barely know what Im doing. This is my first ever Python program and I only made it working with the help of a friend who has bit more experience. If I could I would rewrite the bot in C++ or Java but I didnt find any libs for these languages.

Feel free to make a pull request, I'll have a look at it

**Comment by bstaletic** [comment]
> If I could I would rewrite the bot in C++ or Java but I didnt find any libs for these languages.

Take a look at pybind11 for bridging the C++<->python gap.

**Comment by Narase33** [comment]
How does it behave with python functions returning "anything"? Do I get an std::any or a void*? If thats the case, how much improvement would you see in doing so?

**Comment by bstaletic** [comment]
You can get `py::object`. Then, if you have `py::object o`, you have python API with C++ syntax - `o.attr("member")`/`o.attr("member_func")(args)`, but also `py::isinstance`. For things that don't have a nice interface, you'd end up using a lot of `attr()`, but things like `list` and `dict` have nice APIs in `py::list` and `py::dict`. Also, you get automatic reference counting with `py::object` (and everything derived from it). If ref counting seems expensive, you can be very careful and use `py::handle`, which is just a thin wrapper around `PyObject*`. Handles should be regarded as optimization, though.

There are two ways you can use the library - either embed the interpreter into a C++ application, or write a library in C++ and expose functions/types to python. PyTorch, for example, does the latter.
